<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class FillDataImages extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        $obj = App\Image::create(['path'=>'/assets/img/profil_default.png', 'alt'=>'photo profil par defaut']);
        $obj = App\Image::create(['path'=>'assets/img/public/aaffllz.png', 'alt'=>'hwx']);
        $obj = App\Image::create(['path'=>'assets/img/public/aafflle.png', 'alt'=>'wnd ']);
        $obj = App\Image::create(['path'=>'assets/img/public/aaffllr.png', 'alt'=>'nwx,fj']);
        $obj = App\Image::create(['path'=>'assets/img/public/aaffllt.png', 'alt'=>'sj sbtd']);
        $obj = App\Image::create(['path'=>'assets/img/public/aaffa.png', 'alt'=>'sryj,n']);
        $obj = App\Image::create(['path'=>'assets/img/public/aaffz.png', 'alt'=>'tnduj   jt,n']);
        $obj = App\Image::create(['path'=>'assets/img/public/aaffe.png', 'alt'=>'yxeutcyvik']);
        $obj = App\Image::create(['path'=>'assets/img/public/aaffr.png', 'alt'=>'xjutcr']);
        $obj = App\Image::create(['path'=>'assets/img/public/aajjt.png', 'alt'=>'jcnfuk']);
        $obj = App\Image::create(['path'=>'assets/img/public/aajjy.png', 'alt'=>'x,jxyj']);
        $obj = App\Image::create(['path'=>'assets/img/public/aajju.jpg', 'alt'=>'x,hykxy']);
        $obj = App\Image::create(['path'=>'assets/img/public/aajji.jpg', 'alt'=>'kxy,y,j']);
        $obj = App\Image::create(['path'=>'assets/img/public/aajjo.jpg', 'alt'=>'Lorem']);
        $obj = App\Image::create(['path'=>'assets/img/public/aajjp.jpg', 'alt'=>'tbey']);
        $obj = App\Image::create(['path'=>'assets/img/public/aajjq.jpg', 'alt'=>'</body>']);
        $obj = App\Image::create(['path'=>'assets/img/public/aajjs.jpg', 'alt'=>'vwyx']);
        $obj = App\Image::create(['path'=>'assets/img/public/aajjd.jpg', 'alt'=>'jxcn']);
        $obj = App\Image::create(['path'=>'assets/img/public/aajjf.jpg', 'alt'=>'ky,c']);
        $obj = App\Image::create(['path'=>'assets/img/public/aajjlla.jpg', 'alt'=>'jwxhc']);
        $obj = App\Image::create(['path'=>'assets/img/public/aajjllz.jpg', 'alt'=>'kxjg']);
        $obj = App\Image::create(['path'=>'assets/img/public/bbjjlle.jpg', 'alt'=>'jxh']);
        $obj = App\Image::create(['path'=>'assets/img/public/bbjjllr.jpg', 'alt'=>'jwhxhx']);
        $obj = App\Image::create(['path'=>'assets/img/public/bbjja.jpg', 'alt'=>'hwxgbg']);
        $obj = App\Image::create(['path'=>'assets/img/public/bbjjz.png', 'alt'=>'byjnchn']);
        $obj = App\Image::create(['path'=>'assets/img/public/bbjje.png', 'alt'=>'jwg']);
        $obj = App\Image::create(['path'=>'assets/img/public/bbjjffa.png', 'alt'=>',xjgfb']);
        $obj = App\Image::create(['path'=>'assets/img/public/bbjjffz.png', 'alt'=>'hnxhb']);
        $obj = App\Image::create(['path'=>'assets/img/public/bbjjffe.png', 'alt'=>'jcnhwd']);
        $obj = App\Image::create(['path'=>'assets/img/public/bbjjffr.png', 'alt'=>'gsrwev']);
        $obj = App\Image::create(['path'=>'assets/img/public/bbjjfft.png', 'alt'=>'wsbg']);
        $obj = App\Image::create(['path'=>'assets/img/public/bbjjffy.png', 'alt'=>'whrfbgwd']);
        $obj = App\Image::create(['path'=>'assets/img/public/bbjjfflla.png', 'alt'=>'hwbxfv']);
        $obj = App\Image::create(['path'=>'assets/img/public/bbjjffllz.png', 'alt'=>'hwbxv']);
        $obj = App\Image::create(['path'=>'assets/img/public/bbjjfflle.jpg', 'alt'=>'<shbg']);
        $obj = App\Image::create(['path'=>'assets/img/public/bbjjmmlla.jpg', 'alt'=>'whsg']);
        $obj = App\Image::create(['path'=>'assets/img/public/bbjjmmllz.jpg', 'alt'=>'wgvgw']);
        $obj = App\Image::create(['path'=>'assets/img/public/bbjjmmlle.jpg', 'alt'=>'hqswgx']);
        $obj = App\Image::create(['path'=>'assets/img/public/bbjjmma.png', 'alt'=>'<gwg<gw>gG>gg']);
        $obj = App\Image::create(['path'=>'assets/img/public/bbjjmmz.png', 'alt'=>'<br><br><br>']);
        $obj = App\Image::create(['path'=>'assets/img/public/bbjjmme.png', 'alt'=>'</html>']);
    
        $obj = App\Image::create(['path'=>'assets/img/public/aaaafflla.png', 'alt'=>'yhwrx']);
        $obj = App\Image::create(['path'=>'assets/img/public/aaaaffllz.png', 'alt'=>'hwx']);
        $obj = App\Image::create(['path'=>'assets/img/public/aaaafflle.png', 'alt'=>'wnd ']);
        $obj = App\Image::create(['path'=>'assets/img/public/aaaaffllr.png', 'alt'=>'nwx,fj']);
        $obj = App\Image::create(['path'=>'assets/img/public/aaaaffllt.png', 'alt'=>'sj sbtd']);
        $obj = App\Image::create(['path'=>'assets/img/public/aaaaffa.png', 'alt'=>'sryj,n']);
        $obj = App\Image::create(['path'=>'assets/img/public/aaaaffz.png', 'alt'=>'tnduj   jt,n']);
        $obj = App\Image::create(['path'=>'assets/img/public/aaaaffe.png', 'alt'=>'yxeutcyvik']);
        $obj = App\Image::create(['path'=>'assets/img/public/aaaaffr.png', 'alt'=>'xjutcr']);
        $obj = App\Image::create(['path'=>'assets/img/public/aaaajjt.png', 'alt'=>'jcnfuk']);
        $obj = App\Image::create(['path'=>'assets/img/public/aaaajjy.png', 'alt'=>'x,jxyj']);
        $obj = App\Image::create(['path'=>'assets/img/public/aaaajju.jpg', 'alt'=>'x,hykxy']);
        $obj = App\Image::create(['path'=>'assets/img/public/aaaajji.jpg', 'alt'=>'kxy,y,j']);
        $obj = App\Image::create(['path'=>'assets/img/public/aaaajjo.jpg', 'alt'=>'Lorem']);
        $obj = App\Image::create(['path'=>'assets/img/public/aaaajjp.jpg', 'alt'=>'tbey']);
        $obj = App\Image::create(['path'=>'assets/img/public/aaaajjq.jpg', 'alt'=>'</body>']);
        $obj = App\Image::create(['path'=>'assets/img/public/aaaajjs.jpg', 'alt'=>'vwyx']);
        $obj = App\Image::create(['path'=>'assets/img/public/aaaajjd.jpg', 'alt'=>'jxcn']);
        $obj = App\Image::create(['path'=>'assets/img/public/aaaajjf.jpg', 'alt'=>'ky,c']);
        $obj = App\Image::create(['path'=>'assets/img/public/aaaajjlla.jpg', 'alt'=>'jwxhc']);
        $obj = App\Image::create(['path'=>'assets/img/public/aaaajjllz.jpg', 'alt'=>'kxjg']);
        $obj = App\Image::create(['path'=>'assets/img/public/aabbjjlle.jpg', 'alt'=>'jxh']);
        $obj = App\Image::create(['path'=>'assets/img/public/aabbjjllr.jpg', 'alt'=>'jwhxhx']);
        $obj = App\Image::create(['path'=>'assets/img/public/aabbjja.jpg', 'alt'=>'hwxgbg']);
        $obj = App\Image::create(['path'=>'assets/img/public/aabbjjz.png', 'alt'=>'byjnchn']);
        $obj = App\Image::create(['path'=>'assets/img/public/aabbjje.png', 'alt'=>'jwg']);
        $obj = App\Image::create(['path'=>'assets/img/public/aabbjjffa.png', 'alt'=>',xjgfb']);
        $obj = App\Image::create(['path'=>'assets/img/public/aabbjjffz.png', 'alt'=>'hnxhb']);
        $obj = App\Image::create(['path'=>'assets/img/public/aabbjjffe.png', 'alt'=>'jcnhwd']);
        $obj = App\Image::create(['path'=>'assets/img/public/aabbjjffr.png', 'alt'=>'gsrwev']);
        $obj = App\Image::create(['path'=>'assets/img/public/aabbjjfft.png', 'alt'=>'wsbg']);
        $obj = App\Image::create(['path'=>'assets/img/public/aabbjjffy.png', 'alt'=>'whrfbgwd']);
        $obj = App\Image::create(['path'=>'assets/img/public/aabbjjfflla.png', 'alt'=>'hwbxfv']);
        $obj = App\Image::create(['path'=>'assets/img/public/aabbjjffllz.png', 'alt'=>'hwbxv']);
        $obj = App\Image::create(['path'=>'assets/img/public/aabbjjfflle.jpg', 'alt'=>'<shbg']);
        $obj = App\Image::create(['path'=>'assets/img/public/aabbjjmmlla.jpg', 'alt'=>'whsg']);
        $obj = App\Image::create(['path'=>'assets/img/public/aabbjjmmllz.jpg', 'alt'=>'wgvgw']);
        $obj = App\Image::create(['path'=>'assets/img/public/aabbjjmmlle.jpg', 'alt'=>'hqswgx']);
        $obj = App\Image::create(['path'=>'assets/img/public/aabbjjmma.png', 'alt'=>'<gwg<gw>gG>gg']);
        $obj = App\Image::create(['path'=>'assets/img/public/aabbjjmmz.png', 'alt'=>'<br><br><br>']);
        $obj = App\Image::create(['path'=>'assets/img/public/aabbjjmme.png', 'alt'=>'</html>']);
    
        $obj = App\Image::create(['path'=>'assets/img/public/zzaafflla.png', 'alt'=>'yhwrx']);
        $obj = App\Image::create(['path'=>'assets/img/public/zzaaffllz.png', 'alt'=>'hwx']);
        $obj = App\Image::create(['path'=>'assets/img/public/zzaafflle.png', 'alt'=>'wnd ']);
        $obj = App\Image::create(['path'=>'assets/img/public/zzaaffllr.png', 'alt'=>'nwx,fj']);
        $obj = App\Image::create(['path'=>'assets/img/public/zzaaffllt.png', 'alt'=>'sj sbtd']);
        $obj = App\Image::create(['path'=>'assets/img/public/zzaaffa.png', 'alt'=>'sryj,n']);
        $obj = App\Image::create(['path'=>'assets/img/public/zzaaffz.png', 'alt'=>'tnduj   jt,n']);
        $obj = App\Image::create(['path'=>'assets/img/public/zzaaffe.png', 'alt'=>'yxeutcyvik']);
        $obj = App\Image::create(['path'=>'assets/img/public/zzaaffr.png', 'alt'=>'xjutcr']);
        $obj = App\Image::create(['path'=>'assets/img/public/zzaajjt.png', 'alt'=>'jcnfuk']);
        $obj = App\Image::create(['path'=>'assets/img/public/zzaajjy.png', 'alt'=>'x,jxyj']);
        $obj = App\Image::create(['path'=>'assets/img/public/zzaajju.jpg', 'alt'=>'x,hykxy']);
        $obj = App\Image::create(['path'=>'assets/img/public/zzaajji.jpg', 'alt'=>'kxy,y,j']);
        $obj = App\Image::create(['path'=>'assets/img/public/zzaajjo.jpg', 'alt'=>'Lorem']);
        $obj = App\Image::create(['path'=>'assets/img/public/zzaajjp.jpg', 'alt'=>'tbey']);
        $obj = App\Image::create(['path'=>'assets/img/public/zzaajjq.jpg', 'alt'=>'</body>']);
        $obj = App\Image::create(['path'=>'assets/img/public/zzaajjs.jpg', 'alt'=>'vwyx']);
        $obj = App\Image::create(['path'=>'assets/img/public/zzaajjd.jpg', 'alt'=>'jxcn']);
        $obj = App\Image::create(['path'=>'assets/img/public/zzaajjf.jpg', 'alt'=>'ky,c']);
        $obj = App\Image::create(['path'=>'assets/img/public/zzaajjlla.jpg', 'alt'=>'jwxhc']);
        $obj = App\Image::create(['path'=>'assets/img/public/zzaajjllz.jpg', 'alt'=>'kxjg']);
        $obj = App\Image::create(['path'=>'assets/img/public/zzbbjjlle.jpg', 'alt'=>'jxh']);
        $obj = App\Image::create(['path'=>'assets/img/public/zzbbjjllr.jpg', 'alt'=>'jwhxhx']);
        $obj = App\Image::create(['path'=>'assets/img/public/zzbbjja.jpg', 'alt'=>'hwxgbg']);
        $obj = App\Image::create(['path'=>'assets/img/public/zzbbjjz.png', 'alt'=>'byjnchn']);
        $obj = App\Image::create(['path'=>'assets/img/public/zzbbjje.png', 'alt'=>'jwg']);
        $obj = App\Image::create(['path'=>'assets/img/public/zzbbjjffa.png', 'alt'=>',xjgfb']);
        $obj = App\Image::create(['path'=>'assets/img/public/zzbbjjffz.png', 'alt'=>'hnxhb']);
        $obj = App\Image::create(['path'=>'assets/img/public/zzbbjjffe.png', 'alt'=>'jcnhwd']);
        $obj = App\Image::create(['path'=>'assets/img/public/zzbbjjffr.png', 'alt'=>'gsrwev']);
        $obj = App\Image::create(['path'=>'assets/img/public/zzbbjjfft.png', 'alt'=>'wsbg']);
        $obj = App\Image::create(['path'=>'assets/img/public/zzbbjjffy.png', 'alt'=>'whrfbgwd']);
        $obj = App\Image::create(['path'=>'assets/img/public/zzbbjjfflla.png', 'alt'=>'hwbxfv']);
        $obj = App\Image::create(['path'=>'assets/img/public/zzbbjjffllz.png', 'alt'=>'hwbxv']);
        $obj = App\Image::create(['path'=>'assets/img/public/zzbbjjfflle.jpg', 'alt'=>'<shbg']);
        $obj = App\Image::create(['path'=>'assets/img/public/zzbbjjmmlla.jpg', 'alt'=>'whsg']);
        $obj = App\Image::create(['path'=>'assets/img/public/zzbbjjmmllz.jpg', 'alt'=>'wgvgw']);
        $obj = App\Image::create(['path'=>'assets/img/public/zzbbjjmmlle.jpg', 'alt'=>'hqswgx']);
        $obj = App\Image::create(['path'=>'assets/img/public/zzbbjjmma.png', 'alt'=>'<gwg<gw>gG>gg']);
        $obj = App\Image::create(['path'=>'assets/img/public/zzbbjjmmz.png', 'alt'=>'<br><br><br>']);
        $obj = App\Image::create(['path'=>'assets/img/public/zzbbjjmme.png', 'alt'=>'</html>']);
    
        $obj = App\Image::create(['path'=>'assets/img/public/eeaafflla.png', 'alt'=>'yhwrx']);
        $obj = App\Image::create(['path'=>'assets/img/public/eeaaffllz.png', 'alt'=>'hwx']);
        $obj = App\Image::create(['path'=>'assets/img/public/eeaafflle.png', 'alt'=>'wnd ']);
        $obj = App\Image::create(['path'=>'assets/img/public/eeaaffllr.png', 'alt'=>'nwx,fj']);
        $obj = App\Image::create(['path'=>'assets/img/public/eeaaffllt.png', 'alt'=>'sj sbtd']);
        $obj = App\Image::create(['path'=>'assets/img/public/eeaaffa.png', 'alt'=>'sryj,n']);
        $obj = App\Image::create(['path'=>'assets/img/public/eeaaffz.png', 'alt'=>'tnduj   jt,n']);
        $obj = App\Image::create(['path'=>'assets/img/public/eeaaffe.png', 'alt'=>'yxeutcyvik']);
        $obj = App\Image::create(['path'=>'assets/img/public/eeaaffr.png', 'alt'=>'xjutcr']);
        $obj = App\Image::create(['path'=>'assets/img/public/eeaajjt.png', 'alt'=>'jcnfuk']);
        $obj = App\Image::create(['path'=>'assets/img/public/eeaajjy.png', 'alt'=>'x,jxyj']);
        $obj = App\Image::create(['path'=>'assets/img/public/eeaajju.jpg', 'alt'=>'x,hykxy']);
        $obj = App\Image::create(['path'=>'assets/img/public/eeaajji.jpg', 'alt'=>'kxy,y,j']);
        $obj = App\Image::create(['path'=>'assets/img/public/eeaajjo.jpg', 'alt'=>'Lorem']);
        $obj = App\Image::create(['path'=>'assets/img/public/eeaajjp.jpg', 'alt'=>'tbey']);
        $obj = App\Image::create(['path'=>'assets/img/public/eeaajjq.jpg', 'alt'=>'</body>']);
        $obj = App\Image::create(['path'=>'assets/img/public/eeaajjs.jpg', 'alt'=>'vwyx']);
        $obj = App\Image::create(['path'=>'assets/img/public/eeaajjd.jpg', 'alt'=>'jxcn']);
        $obj = App\Image::create(['path'=>'assets/img/public/eeaajjf.jpg', 'alt'=>'ky,c']);
        $obj = App\Image::create(['path'=>'assets/img/public/eeaajjlla.jpg', 'alt'=>'jwxhc']);
        $obj = App\Image::create(['path'=>'assets/img/public/eeaajjllz.jpg', 'alt'=>'kxjg']);
        $obj = App\Image::create(['path'=>'assets/img/public/eebbjjlle.jpg', 'alt'=>'jxh']);
        $obj = App\Image::create(['path'=>'assets/img/public/eebbjjllr.jpg', 'alt'=>'jwhxhx']);
        $obj = App\Image::create(['path'=>'assets/img/public/eebbjja.jpg', 'alt'=>'hwxgbg']);
        $obj = App\Image::create(['path'=>'assets/img/public/eebbjjz.png', 'alt'=>'byjnchn']);
        $obj = App\Image::create(['path'=>'assets/img/public/eebbjje.png', 'alt'=>'jwg']);
        $obj = App\Image::create(['path'=>'assets/img/public/eebbjjffa.png', 'alt'=>',xjgfb']);
        $obj = App\Image::create(['path'=>'assets/img/public/eebbjjffz.png', 'alt'=>'hnxhb']);
        $obj = App\Image::create(['path'=>'assets/img/public/eebbjjffe.png', 'alt'=>'jcnhwd']);
        $obj = App\Image::create(['path'=>'assets/img/public/eebbjjffr.png', 'alt'=>'gsrwev']);
        $obj = App\Image::create(['path'=>'assets/img/public/eebbjjfft.png', 'alt'=>'wsbg']);
        $obj = App\Image::create(['path'=>'assets/img/public/eebbjjffy.png', 'alt'=>'whrfbgwd']);
        $obj = App\Image::create(['path'=>'assets/img/public/eebbjjfflla.png', 'alt'=>'hwbxfv']);
        $obj = App\Image::create(['path'=>'assets/img/public/eebbjjffllz.png', 'alt'=>'hwbxv']);
        $obj = App\Image::create(['path'=>'assets/img/public/eebbjjfflle.jpg', 'alt'=>'<shbg']);
        $obj = App\Image::create(['path'=>'assets/img/public/eebbjjmmlla.jpg', 'alt'=>'whsg']);
        $obj = App\Image::create(['path'=>'assets/img/public/eebbjjmmllz.jpg', 'alt'=>'wgvgw']);
        $obj = App\Image::create(['path'=>'assets/img/public/eebbjjmmlle.jpg', 'alt'=>'hqswgx']);
        $obj = App\Image::create(['path'=>'assets/img/public/eebbjjmma.png', 'alt'=>'<gwg<gw>gG>gg']);
        $obj = App\Image::create(['path'=>'assets/img/public/eebbjjmmz.png', 'alt'=>'<br><br><br>']);
        $obj = App\Image::create(['path'=>'assets/img/public/eebbjjmme.png', 'alt'=>'</html>']);
    
        $obj = App\Image::create(['path'=>'assets/img/public/rraafflla.png', 'alt'=>'yhwrx']);
        $obj = App\Image::create(['path'=>'assets/img/public/rraaffllz.png', 'alt'=>'hwx']);
        $obj = App\Image::create(['path'=>'assets/img/public/rraafflle.png', 'alt'=>'wnd ']);
        $obj = App\Image::create(['path'=>'assets/img/public/rraaffllr.png', 'alt'=>'nwx,fj']);
        $obj = App\Image::create(['path'=>'assets/img/public/rraaffllt.png', 'alt'=>'sj sbtd']);
        $obj = App\Image::create(['path'=>'assets/img/public/rraaffa.png', 'alt'=>'sryj,n']);
        $obj = App\Image::create(['path'=>'assets/img/public/rraaffz.png', 'alt'=>'tnduj   jt,n']);
        $obj = App\Image::create(['path'=>'assets/img/public/rraaffe.png', 'alt'=>'yxeutcyvik']);
        $obj = App\Image::create(['path'=>'assets/img/public/rraaffr.png', 'alt'=>'xjutcr']);
        $obj = App\Image::create(['path'=>'assets/img/public/rraajjt.png', 'alt'=>'jcnfuk']);
        $obj = App\Image::create(['path'=>'assets/img/public/rraajjy.png', 'alt'=>'x,jxyj']);
        $obj = App\Image::create(['path'=>'assets/img/public/rraajju.jpg', 'alt'=>'x,hykxy']);
        $obj = App\Image::create(['path'=>'assets/img/public/rraajji.jpg', 'alt'=>'kxy,y,j']);
        $obj = App\Image::create(['path'=>'assets/img/public/rraajjo.jpg', 'alt'=>'Lorem']);
        $obj = App\Image::create(['path'=>'assets/img/public/rraajjp.jpg', 'alt'=>'tbey']);
        $obj = App\Image::create(['path'=>'assets/img/public/rraajjq.jpg', 'alt'=>'</body>']);
        $obj = App\Image::create(['path'=>'assets/img/public/rraajjs.jpg', 'alt'=>'vwyx']);
        $obj = App\Image::create(['path'=>'assets/img/public/rraajjd.jpg', 'alt'=>'jxcn']);
        $obj = App\Image::create(['path'=>'assets/img/public/rraajjf.jpg', 'alt'=>'ky,c']);
        $obj = App\Image::create(['path'=>'assets/img/public/rraajjlla.jpg', 'alt'=>'jwxhc']);
        $obj = App\Image::create(['path'=>'assets/img/public/rraajjllz.jpg', 'alt'=>'kxjg']);
        $obj = App\Image::create(['path'=>'assets/img/public/rrbbjjlle.jpg', 'alt'=>'jxh']);
        $obj = App\Image::create(['path'=>'assets/img/public/rrbbjjllr.jpg', 'alt'=>'jwhxhx']);
        $obj = App\Image::create(['path'=>'assets/img/public/rrbbjja.jpg', 'alt'=>'hwxgbg']);
        $obj = App\Image::create(['path'=>'assets/img/public/rrbbjjz.png', 'alt'=>'byjnchn']);
        $obj = App\Image::create(['path'=>'assets/img/public/rrbbjje.png', 'alt'=>'jwg']);
        $obj = App\Image::create(['path'=>'assets/img/public/rrbbjjffa.png', 'alt'=>',xjgfb']);
        $obj = App\Image::create(['path'=>'assets/img/public/rrbbjjffz.png', 'alt'=>'hnxhb']);
        $obj = App\Image::create(['path'=>'assets/img/public/rrbbjjffe.png', 'alt'=>'jcnhwd']);
        $obj = App\Image::create(['path'=>'assets/img/public/rrbbjjffr.png', 'alt'=>'gsrwev']);
        $obj = App\Image::create(['path'=>'assets/img/public/rrbbjjfft.png', 'alt'=>'wsbg']);
        $obj = App\Image::create(['path'=>'assets/img/public/rrbbjjffy.png', 'alt'=>'whrfbgwd']);
        $obj = App\Image::create(['path'=>'assets/img/public/rrbbjjfflla.png', 'alt'=>'hwbxfv']);
        $obj = App\Image::create(['path'=>'assets/img/public/rrbbjjffllz.png', 'alt'=>'hwbxv']);
        $obj = App\Image::create(['path'=>'assets/img/public/rrbbjjfflle.jpg', 'alt'=>'<shbg']);
        $obj = App\Image::create(['path'=>'/assets/img/articles/tasse_bambou_lyon.png', 'alt'=>'tasse en bambou']);
        $obj = App\Image::create(['path'=>'/assets/img/articles/stylo_bleu_cesi.png', 'alt'=>'stylo cesi bleu']);
        $obj = App\Image::create(['path'=>'/assets/img/articles/stylo_blanc_cesi.png', 'alt'=>'stylo cesi blanc']);
        $obj = App\Image::create(['path'=>'/assets/img/articles/stylo_rouge_cesi.png', 'alt'=>'stylo cesi rouge']);
        $obj = App\Image::create(['path'=>'/assets/img/articles/sweat_bleu.jpg', 'alt'=>'sweat BDE lyon']);
        $obj = App\Image::create(['path'=>'/assets/img/articles/sweat_bleu.jpg', 'alt'=>'sweat BDE paris']);
    
        $obj = App\Image::create(['path'=>'/assets/img/articles/sweat_bleu.jpg', 'alt'=>'sweat BDE rouen']);
        $obj = App\Image::create(['path'=>'/assets/img/articles/sweat_bleu.jpg', 'alt'=>'sweat cesi']);
        $obj = App\Image::create(['path'=>'/assets/img/articles/cable_hdmi.jpg', 'alt'=>'cable hdmi']);
        $obj = App\Image::create(['path'=>'/assets/img/articles/cable_vga.jpg', 'alt'=>'cable vga']);
        $obj = App\Image::create(['path'=>'/assets/img/articles/montre_acier.png', 'alt'=>'montre acier']);
        $obj = App\Image::create(['path'=>'/assets/img/articles/montre_bois.jpg', 'alt'=>'montre bois']);
        $obj = App\Image::create(['path'=>'/assets/img/articles/sticker_voiture_geant.jpg', 'alt'=>'sticker voiture geant']);
        $obj = App\Image::create(['path'=>'/assets/img/articles/livre_html5_css3.jpg', 'alt'=>'livre apprendre html5 css3']);
        $obj = App\Image::create(['path'=>'/assets/img/articles/apprendre_php7.jpg', 'alt'=>'apprendre php7 3 heures']);
        $obj = App\Image::create(['path'=>'/assets/img/articles/apprendre_laravel.jpg', 'alt'=>'laravel pour les pros']);
        $obj = App\Image::create(['path'=>'/assets/img/articles/carte_arduino_uno.jpg', 'alt'=>'carte arduino uno']);
        $obj = App\Image::create(['path'=>'/assets/img/articles/carte_raspberry_pi.jpg', 'alt'=>'carte raspberry pi']);
        $obj = App\Image::create(['path'=>'/assets/img/articles/tee_shirt_noir.jpg', 'alt'=>'tee-shirt noir']);
        $obj = App\Image::create(['path'=>'/assets/img/articles/chaise_en_bois.jpg', 'alt'=>'chaise en bois']);
        $obj = App\Image::create(['path'=>'/assets/img/articles/cartable_cours.jpg', 'alt'=>'cartable cours cesi']);
        $obj = App\Image::create(['path'=>'/assets/img/articles/chaussure_de_ville.jpg', 'alt'=>'chaussure de ville']);
        $obj = App\Image::create(['path'=>'/assets/img/articles/chaussure_de_sport.jpg', 'alt'=>'chaussure de sport']);
        $obj = App\Image::create(['path'=>'/assets/img/articles/ballon_foot.jpg', 'alt'=>'ballon de foot']);
        $obj = App\Image::create(['path'=>'/assets/img/articles/ballon_rugby.jpg', 'alt'=>'ballon de rugby']);
        $obj = App\Image::create(['path'=>'assets/img/public/ttaajjlla.jpg', 'alt'=>'jwxhc']);
        $obj = App\Image::create(['path'=>'assets/img/public/ttaajjllz.jpg', 'alt'=>'kxjg']);
        $obj = App\Image::create(['path'=>'assets/img/public/ttbbjjlle.jpg', 'alt'=>'jxh']);
        $obj = App\Image::create(['path'=>'assets/img/public/ttbbjjllr.jpg', 'alt'=>'jwhxhx']);
        $obj = App\Image::create(['path'=>'assets/img/public/ttbbjja.jpg', 'alt'=>'hwxgbg']);
        $obj = App\Image::create(['path'=>'assets/img/public/ttbbjjz.png', 'alt'=>'byjnchn']);
        $obj = App\Image::create(['path'=>'assets/img/public/ttbbjje.png', 'alt'=>'jwg']);
        $obj = App\Image::create(['path'=>'assets/img/public/ttbbjjffa.png', 'alt'=>',xjgfb']);
        $obj = App\Image::create(['path'=>'assets/img/public/ttbbjjffz.png', 'alt'=>'hnxhb']);
        $obj = App\Image::create(['path'=>'assets/img/public/ttbbjjffe.png', 'alt'=>'jcnhwd']);
        $obj = App\Image::create(['path'=>'assets/img/public/ttbbjjffr.png', 'alt'=>'gsrwev']);
        $obj = App\Image::create(['path'=>'assets/img/public/ttbbjjfft.png', 'alt'=>'wsbg']);
        $obj = App\Image::create(['path'=>'assets/img/public/ttbbjjffy.png', 'alt'=>'whrfbgwd']);
        $obj = App\Image::create(['path'=>'assets/img/public/ttbbjjfflla.png', 'alt'=>'hwbxfv']);
        $obj = App\Image::create(['path'=>'assets/img/public/ttbbjjffllz.png', 'alt'=>'hwbxv']);
        $obj = App\Image::create(['path'=>'assets/img/public/ttbbjjfflle.jpg', 'alt'=>'<shbg']);
        $obj = App\Image::create(['path'=>'assets/img/public/ttbbjjmmlla.jpg', 'alt'=>'whsg']);
        $obj = App\Image::create(['path'=>'assets/img/public/ttbbjjmmllz.jpg', 'alt'=>'wgvgw']);
        $obj = App\Image::create(['path'=>'assets/img/public/ttbbjjmmlle.jpg', 'alt'=>'hqswgx']);
        $obj = App\Image::create(['path'=>'assets/img/public/ttbbjjmma.png', 'alt'=>'<gwg<gw>gG>gg']);
        $obj = App\Image::create(['path'=>'assets/img/public/ttbbjjmmz.png', 'alt'=>'<br><br><br>']);
        $obj = App\Image::create(['path'=>'assets/img/public/ttbbjjmme.png', 'alt'=>'</html>']);
    
        $obj = App\Image::create(['path'=>'assets/img/public/aattaafflla.png', 'alt'=>'yhwrx']);
        $obj = App\Image::create(['path'=>'assets/img/public/aattaaffllz.png', 'alt'=>'hwx']);
        $obj = App\Image::create(['path'=>'assets/img/public/aattaafflle.png', 'alt'=>'wnd ']);
        $obj = App\Image::create(['path'=>'/assets/img/events/jeux_de_role.png', 'alt'=>'jeux de rôles']);
        $obj = App\Image::create(['path'=>'/assets/img/events/cinema.jpg', 'alt'=>'cinéma']);
        $obj = App\Image::create(['path'=>'/assets/img/events/football.jpg', 'alt'=>'foot']);
        $obj = App\Image::create(['path'=>'/assets/img/events/jardinage.jpg', 'alt'=>'jardinage']);
        $obj = App\Image::create(['path'=>'/assets/img/events/rugby.jpg', 'alt'=>'rugby']);
        $obj = App\Image::create(['path'=>'/assets/img/events/patinoire.jpg', 'alt'=>'patinoire']);
        $obj = App\Image::create(['path'=>'/assets/img/events/sortie_ski.jpg', 'alt'=>'sortie ski']);
        $obj = App\Image::create(['path'=>'/assets/img/events/creation_borne_arcade.jpg', 'alt'=>'fablab bornes arcades']);
        $obj = App\Image::create(['path'=>'/assets/img/events/atelier_couture.jpg', 'alt'=>'atelier couture']);
        $obj = App\Image::create(['path'=>'assets/img/public/aattaajji.jpg', 'alt'=>'kxy,y,j']);
        $obj = App\Image::create(['path'=>'/assets/img/events/battle_dev.jpg', 'alt'=>'battle dev']);
        $obj = App\Image::create(['path'=>'/assets/img/events/nuit_info.jpg', 'alt'=>'nuit de l info']);
        $obj = App\Image::create(['path'=>'/assets/img/events/mario_kart_wii.jpg', 'alt'=>'mario kart wii']);
        $obj = App\Image::create(['path'=>'/assets/img/events/theatre.jpg', 'alt'=>'théâtre']);
        $obj = App\Image::create(['path'=>'/assets/img/events/ping_pong.jpg', 'alt'=>'ping pong']);
        $obj = App\Image::create(['path'=>'assets/img/public/aattaajjf.jpg', 'alt'=>'ky,c']);
        $obj = App\Image::create(['path'=>'assets/img/public/aattaajjlla.jpg', 'alt'=>'jwxhc']);
        $obj = App\Image::create(['path'=>'assets/img/public/aattaajjllz.jpg', 'alt'=>'kxjg']);
        $obj = App\Image::create(['path'=>'assets/img/public/aattbbjjlle.jpg', 'alt'=>'jxh']);
        $obj = App\Image::create(['path'=>'assets/img/public/aattbbjjllr.jpg', 'alt'=>'jwhxhx']);
        $obj = App\Image::create(['path'=>'assets/img/public/aattbbjja.jpg', 'alt'=>'hwxgbg']);
        $obj = App\Image::create(['path'=>'assets/img/public/aattbbjjz.png', 'alt'=>'byjnchn']);
        $obj = App\Image::create(['path'=>'assets/img/public/aattbbjje.png', 'alt'=>'jwg']);
        $obj = App\Image::create(['path'=>'assets/img/public/aattbbjjffa.png', 'alt'=>',xjgfb']);
        $obj = App\Image::create(['path'=>'assets/img/public/aattbbjjffz.png', 'alt'=>'hnxhb']);
        $obj = App\Image::create(['path'=>'assets/img/public/aattbbjjffe.png', 'alt'=>'jcnhwd']);
        $obj = App\Image::create(['path'=>'assets/img/public/aattbbjjffr.png', 'alt'=>'gsrwev']);
        $obj = App\Image::create(['path'=>'assets/img/public/aattbbjjfft.png', 'alt'=>'wsbg']);
        $obj = App\Image::create(['path'=>'assets/img/public/aattbbjjffy.png', 'alt'=>'whrfbgwd']);
        $obj = App\Image::create(['path'=>'assets/img/public/aattbbjjfflla.png', 'alt'=>'hwbxfv']);
        $obj = App\Image::create(['path'=>'assets/img/public/aattbbjjffllz.png', 'alt'=>'hwbxv']);
        $obj = App\Image::create(['path'=>'assets/img/public/aattbbjjfflle.jpg', 'alt'=>'<shbg']);
        $obj = App\Image::create(['path'=>'assets/img/public/aattbbjjmmlla.jpg', 'alt'=>'whsg']);
        $obj = App\Image::create(['path'=>'assets/img/public/aattbbjjmmllz.jpg', 'alt'=>'wgvgw']);
        $obj = App\Image::create(['path'=>'assets/img/public/aattbbjjmmlle.jpg', 'alt'=>'hqswgx']);
        $obj = App\Image::create(['path'=>'assets/img/public/aattbbjjmma.png', 'alt'=>'<gwg<gw>gG>gg']);
        $obj = App\Image::create(['path'=>'assets/img/public/aattbbjjmmz.png', 'alt'=>'<br><br><br>']);
        $obj = App\Image::create(['path'=>'assets/img/public/aattbbjjmme.png', 'alt'=>'</html>']);
    
        $obj = App\Image::create(['path'=>'assets/img/public/ttaafflla.png', 'alt'=>'yhwrx']);
        $obj = App\Image::create(['path'=>'assets/img/public/ttaaffllz.png', 'alt'=>'hwx']);
        $obj = App\Image::create(['path'=>'assets/img/public/ttaafflle.png', 'alt'=>'wnd ']);
        $obj = App\Image::create(['path'=>'assets/img/public/ttaaffllr.png', 'alt'=>'nwx,fj']);
        $obj = App\Image::create(['path'=>'assets/img/public/ttaaffllt.png', 'alt'=>'sj sbtd']);
        $obj = App\Image::create(['path'=>'assets/img/public/ttaaffa.png', 'alt'=>'sryj,n']);
        $obj = App\Image::create(['path'=>'assets/img/public/ttaaffz.png', 'alt'=>'tnduj   jt,n']);
        $obj = App\Image::create(['path'=>'assets/img/public/ttaaffe.png', 'alt'=>'yxeutcyvik']);
        $obj = App\Image::create(['path'=>'assets/img/public/ttaaffr.png', 'alt'=>'xjutcr']);
        $obj = App\Image::create(['path'=>'assets/img/public/ttaajjt.png', 'alt'=>'jcnfuk']);
        $obj = App\Image::create(['path'=>'assets/img/public/ttaajjy.png', 'alt'=>'x,jxyj']);
        $obj = App\Image::create(['path'=>'assets/img/public/ttaajju.jpg', 'alt'=>'x,hykxy']);
        $obj = App\Image::create(['path'=>'assets/img/public/ttaajji.jpg', 'alt'=>'kxy,y,j']);
        $obj = App\Image::create(['path'=>'assets/img/public/ttaajjo.jpg', 'alt'=>'Lorem']);
        $obj = App\Image::create(['path'=>'assets/img/public/ttaajjp.jpg', 'alt'=>'tbey']);
        $obj = App\Image::create(['path'=>'assets/img/public/ttaajjq.jpg', 'alt'=>'</body>']);
        $obj = App\Image::create(['path'=>'assets/img/public/ttaajjs.jpg', 'alt'=>'vwyx']);
        $obj = App\Image::create(['path'=>'assets/img/public/ttaajjd.jpg', 'alt'=>'jxcn']);
        $obj = App\Image::create(['path'=>'assets/img/public/ttaajjf.jpg', 'alt'=>'ky,c']);
        $obj = App\Image::create(['path'=>'assets/img/public/ttaajjlla.jpg', 'alt'=>'jwxhc']);
        $obj = App\Image::create(['path'=>'assets/img/public/ttaajjllz.jpg', 'alt'=>'kxjg']);
        $obj = App\Image::create(['path'=>'assets/img/public/ttbbjjlle.jpg', 'alt'=>'jxh']);
        $obj = App\Image::create(['path'=>'assets/img/public/ttbbjjllr.jpg', 'alt'=>'jwhxhx']);
        $obj = App\Image::create(['path'=>'assets/img/public/ttbbjja.jpg', 'alt'=>'hwxgbg']);
        $obj = App\Image::create(['path'=>'assets/img/public/ttbbjjz.png', 'alt'=>'byjnchn']);
        $obj = App\Image::create(['path'=>'assets/img/public/ttbbjje.png', 'alt'=>'jwg']);
        $obj = App\Image::create(['path'=>'assets/img/public/ttbbjjffa.png', 'alt'=>',xjgfb']);
        $obj = App\Image::create(['path'=>'assets/img/public/ttbbjjffz.png', 'alt'=>'hnxhb']);
        $obj = App\Image::create(['path'=>'assets/img/public/ttbbjjffe.png', 'alt'=>'jcnhwd']);
        $obj = App\Image::create(['path'=>'assets/img/public/ttbbjjffr.png', 'alt'=>'gsrwev']);
        $obj = App\Image::create(['path'=>'assets/img/public/ttbbjjfft.png', 'alt'=>'wsbg']);
        $obj = App\Image::create(['path'=>'assets/img/public/ttbbjjffy.png', 'alt'=>'whrfbgwd']);
        $obj = App\Image::create(['path'=>'assets/img/public/ttbbjjfflla.png', 'alt'=>'hwbxfv']);
        $obj = App\Image::create(['path'=>'assets/img/public/ttbbjjffllz.png', 'alt'=>'hwbxv']);
        $obj = App\Image::create(['path'=>'assets/img/public/ttbbjjfflle.jpg', 'alt'=>'<shbg']);
        $obj = App\Image::create(['path'=>'assets/img/public/ttbbjjmmlla.jpg', 'alt'=>'whsg']);
        $obj = App\Image::create(['path'=>'assets/img/public/ttbbjjmmllz.jpg', 'alt'=>'wgvgw']);
        $obj = App\Image::create(['path'=>'assets/img/public/ttbbjjmmlle.jpg', 'alt'=>'hqswgx']);
        $obj = App\Image::create(['path'=>'assets/img/public/ttbbjjmma.png', 'alt'=>'<gwg<gw>gG>gg']);
        $obj = App\Image::create(['path'=>'assets/img/public/ttbbjjmmz.png', 'alt'=>'<br><br><br>']);
        $obj = App\Image::create(['path'=>'assets/img/public/ttbbjjmme.png', 'alt'=>'</html>']);
    
        $obj = App\Image::create(['path'=>'assets/img/public/eettaafflla.png', 'alt'=>'yhwrx']);
        $obj = App\Image::create(['path'=>'assets/img/public/eettaaffllz.png', 'alt'=>'hwx']);
        $obj = App\Image::create(['path'=>'assets/img/public/eettaafflle.png', 'alt'=>'wnd ']);
        $obj = App\Image::create(['path'=>'assets/img/public/eettaaffllr.png', 'alt'=>'nwx,fj']);
        $obj = App\Image::create(['path'=>'assets/img/public/eettaaffllt.png', 'alt'=>'sj sbtd']);
        $obj = App\Image::create(['path'=>'assets/img/public/eettaaffa.png', 'alt'=>'sryj,n']);
        $obj = App\Image::create(['path'=>'assets/img/public/eettaaffz.png', 'alt'=>'tnduj   jt,n']);
        $obj = App\Image::create(['path'=>'assets/img/public/eettaaffe.png', 'alt'=>'yxeutcyvik']);
        $obj = App\Image::create(['path'=>'assets/img/public/eettaaffr.png', 'alt'=>'xjutcr']);
        $obj = App\Image::create(['path'=>'assets/img/public/eettaajjt.png', 'alt'=>'jcnfuk']);
        $obj = App\Image::create(['path'=>'assets/img/public/eettaajjy.png', 'alt'=>'x,jxyj']);
        $obj = App\Image::create(['path'=>'assets/img/public/eettaajju.jpg', 'alt'=>'x,hykxy']);
        $obj = App\Image::create(['path'=>'assets/img/public/eettaajji.jpg', 'alt'=>'kxy,y,j']);
        $obj = App\Image::create(['path'=>'assets/img/public/eettaajjo.jpg', 'alt'=>'Lorem']);
        $obj = App\Image::create(['path'=>'assets/img/public/eettaajjp.jpg', 'alt'=>'tbey']);
        $obj = App\Image::create(['path'=>'assets/img/public/eettaajjq.jpg', 'alt'=>'</body>']);
        $obj = App\Image::create(['path'=>'assets/img/public/eettaajjs.jpg', 'alt'=>'vwyx']);
        $obj = App\Image::create(['path'=>'assets/img/public/eettaajjd.jpg', 'alt'=>'jxcn']);
        $obj = App\Image::create(['path'=>'assets/img/public/eettaajjf.jpg', 'alt'=>'ky,c']);
        $obj = App\Image::create(['path'=>'assets/img/public/eettaajjlla.jpg', 'alt'=>'jwxhc']);
        $obj = App\Image::create(['path'=>'assets/img/public/eettaajjllz.jpg', 'alt'=>'kxjg']);
        $obj = App\Image::create(['path'=>'assets/img/public/eettbbjjlle.jpg', 'alt'=>'jxh']);
        $obj = App\Image::create(['path'=>'assets/img/public/eettbbjjllr.jpg', 'alt'=>'jwhxhx']);
        $obj = App\Image::create(['path'=>'assets/img/public/eettbbjja.jpg', 'alt'=>'hwxgbg']);
        $obj = App\Image::create(['path'=>'assets/img/public/eettbbjjz.png', 'alt'=>'byjnchn']);
        $obj = App\Image::create(['path'=>'assets/img/public/eettbbjje.png', 'alt'=>'jwg']);
        $obj = App\Image::create(['path'=>'assets/img/public/eettbbjjffa.png', 'alt'=>',xjgfb']);
        $obj = App\Image::create(['path'=>'assets/img/public/eettbbjjffz.png', 'alt'=>'hnxhb']);
        $obj = App\Image::create(['path'=>'assets/img/public/eettbbjjffe.png', 'alt'=>'jcnhwd']);
        $obj = App\Image::create(['path'=>'assets/img/public/eettbbjjffr.png', 'alt'=>'gsrwev']);
        $obj = App\Image::create(['path'=>'assets/img/public/eettbbjjfft.png', 'alt'=>'wsbg']);
        $obj = App\Image::create(['path'=>'assets/img/public/eettbbjjffy.png', 'alt'=>'whrfbgwd']);
        $obj = App\Image::create(['path'=>'assets/img/public/eettbbjjfflla.png', 'alt'=>'hwbxfv']);
        $obj = App\Image::create(['path'=>'assets/img/public/eettbbjjffllz.png', 'alt'=>'hwbxv']);
        $obj = App\Image::create(['path'=>'assets/img/public/eettbbjjfflle.jpg', 'alt'=>'<shbg']);
        $obj = App\Image::create(['path'=>'assets/img/public/eettbbjjmmlla.jpg', 'alt'=>'whsg']);
        $obj = App\Image::create(['path'=>'assets/img/public/eettbbjjmmllz.jpg', 'alt'=>'wgvgw']);
        $obj = App\Image::create(['path'=>'assets/img/public/eettbbjjmmlle.jpg', 'alt'=>'hqswgx']);
        $obj = App\Image::create(['path'=>'assets/img/public/eettbbjjmma.png', 'alt'=>'<gwg<gw>gG>gg']);
        $obj = App\Image::create(['path'=>'assets/img/public/eettbbjjmmz.png', 'alt'=>'<br><br><br>']);
        $obj = App\Image::create(['path'=>'assets/img/public/eettbbjjmme.png', 'alt'=>'</html>']);
    
        $obj = App\Image::create(['path'=>'assets/img/public/rrttaafflla.png', 'alt'=>'yhwrx']);
        $obj = App\Image::create(['path'=>'assets/img/public/rrttaaffllz.png', 'alt'=>'hwx']);
        $obj = App\Image::create(['path'=>'assets/img/public/rrttaafflle.png', 'alt'=>'wnd ']);
        $obj = App\Image::create(['path'=>'assets/img/public/rrttaaffllr.png', 'alt'=>'nwx,fj']);
        $obj = App\Image::create(['path'=>'assets/img/public/rrttaaffllt.png', 'alt'=>'sj sbtd']);
        $obj = App\Image::create(['path'=>'assets/img/public/rrttaaffa.png', 'alt'=>'sryj,n']);
        $obj = App\Image::create(['path'=>'assets/img/public/rrttaaffz.png', 'alt'=>'tnduj   jt,n']);
        $obj = App\Image::create(['path'=>'assets/img/public/rrttaaffe.png', 'alt'=>'yxeutcyvik']);
        $obj = App\Image::create(['path'=>'assets/img/public/rrttaaffr.png', 'alt'=>'xjutcr']);
        $obj = App\Image::create(['path'=>'assets/img/public/rrttaajjt.png', 'alt'=>'jcnfuk']);
        $obj = App\Image::create(['path'=>'assets/img/public/rrttaajjy.png', 'alt'=>'x,jxyj']);
        $obj = App\Image::create(['path'=>'assets/img/public/rrttaajju.jpg', 'alt'=>'x,hykxy']);
        $obj = App\Image::create(['path'=>'assets/img/public/rrttaajji.jpg', 'alt'=>'kxy,y,j']);
        $obj = App\Image::create(['path'=>'assets/img/public/rrttaajjo.jpg', 'alt'=>'Lorem']);
        $obj = App\Image::create(['path'=>'assets/img/public/rrttaajjp.jpg', 'alt'=>'tbey']);
        $obj = App\Image::create(['path'=>'assets/img/public/rrttaajjq.jpg', 'alt'=>'</body>']);
        $obj = App\Image::create(['path'=>'assets/img/public/rrttaajjs.jpg', 'alt'=>'vwyx']);
        $obj = App\Image::create(['path'=>'assets/img/public/rrttaajjd.jpg', 'alt'=>'jxcn']);
        $obj = App\Image::create(['path'=>'assets/img/public/rrttaajjf.jpg', 'alt'=>'ky,c']);
        $obj = App\Image::create(['path'=>'assets/img/public/rrttaajjlla.jpg', 'alt'=>'jwxhc']);
        $obj = App\Image::create(['path'=>'assets/img/public/rrttaajjllz.jpg', 'alt'=>'kxjg']);
        $obj = App\Image::create(['path'=>'assets/img/public/rrttbbjjlle.jpg', 'alt'=>'jxh']);
        $obj = App\Image::create(['path'=>'assets/img/public/rrttbbjjllr.jpg', 'alt'=>'jwhxhx']);
        $obj = App\Image::create(['path'=>'assets/img/public/rrttbbjja.jpg', 'alt'=>'hwxgbg']);
        $obj = App\Image::create(['path'=>'assets/img/public/rrttbbjjz.png', 'alt'=>'byjnchn']);
        $obj = App\Image::create(['path'=>'assets/img/public/rrttbbjje.png', 'alt'=>'jwg']);
        $obj = App\Image::create(['path'=>'assets/img/public/rrttbbjjffa.png', 'alt'=>',xjgfb']);
        $obj = App\Image::create(['path'=>'assets/img/public/rrttbbjjffz.png', 'alt'=>'hnxhb']);
        $obj = App\Image::create(['path'=>'assets/img/public/rrttbbjjffe.png', 'alt'=>'jcnhwd']);
        $obj = App\Image::create(['path'=>'assets/img/public/rrttbbjjffr.png', 'alt'=>'gsrwev']);
        $obj = App\Image::create(['path'=>'assets/img/public/rrttbbjjfft.png', 'alt'=>'wsbg']);
        $obj = App\Image::create(['path'=>'assets/img/public/rrttbbjjffy.png', 'alt'=>'whrfbgwd']);
        $obj = App\Image::create(['path'=>'assets/img/public/rrttbbjjfflla.png', 'alt'=>'hwbxfv']);
        $obj = App\Image::create(['path'=>'assets/img/public/rrttbbjjffllz.png', 'alt'=>'hwbxv']);
        $obj = App\Image::create(['path'=>'assets/img/public/rrttbbjjfflle.jpg', 'alt'=>'<shbg']);
        $obj = App\Image::create(['path'=>'assets/img/public/rrttbbjjmmlla.jpg', 'alt'=>'whsg']);
        $obj = App\Image::create(['path'=>'assets/img/public/rrttbbjjmmllz.jpg', 'alt'=>'wgvgw']);
        $obj = App\Image::create(['path'=>'assets/img/public/rrttbbjjmmlle.jpg', 'alt'=>'hqswgx']);
        $obj = App\Image::create(['path'=>'assets/img/public/rrttbbjjmma.png', 'alt'=>'<gwg<gw>gG>gg']);
        $obj = App\Image::create(['path'=>'assets/img/public/rrttbbjjmmz.png', 'alt'=>'<br><br><br>']);
        $obj = App\Image::create(['path'=>'assets/img/public/rrttbbjjmme.png', 'alt'=>'</html>']);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        //
    }
}
