<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class FillDataPosts extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $obj = App\Post::create(['text'=>'Génial !', 'date'=>'2019-12-01', 'id_users'=>'1', 'id_events'=>'1']);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                   $obj = App\Post::create(['text'=>'Cool !', 'date'=>'2019-12-01', 'id_users'=>'5', 'id_events'=>'1']);
                                                                                                                                                                                                                                                                                                                                                                                                                                                 $obj = App\Post::create(['text'=>'Pas compris le principe.', 'date'=>'2019-12-01', 'id_users'=>'6', 'id_events'=>'1']);
                                                                $obj = App\Post::create(['text'=>'Amet occaecat nisi qui et aute excepteur velit eiusmod dolor magna elit. Tempor tempor nisi est officia laborum pariatur irure anim aute exercitation culpa eu occaecat excepteur. Cupidatat occaecat culpa sint aliquip cillum laborum magna officia cillum occaecat. Cupidatat dolor dolor esse cillum enim ea. Commodo nulla ex Lorem incididunt officia irure in cupidatat dolor Lorem Lorem commodo.', 'date'=>'2019-12-08', 'id_users'=>'4', 'id_events'=>'3']);
        $obj = App\Post::create(['text'=>'Lorem cillum quis ad commodo eiusmod ad ut incididunt reprehenderit in nisi. Enim et deserunt qui ut. Nostrud do anim aliqua qui nisi veniam quis magna cillum. Ipsum et commodo officia cillum. Sint pariatur est officia sint reprehenderit ad irure proident pariatur deserunt incididunt officia duis cupidatat. Aute deserunt tempor cupidatat est adipisicing sit magna culpa Lorem non aute esse Lorem. Eu anim est elit amet anim minim dolor Lorem amet.', 'date'=>'2019-12-06', 'id_users'=>'2', 'id_events'=>'2']);
                                                                                                                                                                                                                                                                                                                                                                                                                                                               $obj = App\Post::create(['text'=>'Trop long.', 'date'=>'2019-12-12', 'id_users'=>'9', 'id_events'=>'2']);
                                                                                                                                                                                                                                                                                                                                                                                                                                     $obj = App\Post::create(['text'=>'Venez nombreux, on a besoin de monde', 'date'=>'2019-12-16', 'id_users'=>'8', 'id_events'=>'2']);
                                                                                                                                                                                                                                                                                                                                                                                              $obj = App\Post::create(['text'=>'Ea commodo ad voluptate ea sunt qui anim do sit excepteur nostrud sint qui.', 'date'=>'2019-12-18', 'id_users'=>'7', 'id_events'=>'3']);
                                                                                                                                                                                                                                                                                                                                                                                                                                                    $obj = App\Post::create(['text'=>'Il faut plus de bois.', 'date'=>'2019-12-14', 'id_users'=>'5', 'id_events'=>'3']);
                                                                                                                                                                                                                                                                                                                                                                                                                                                              $obj = App\Post::create(['text'=>'Très bien ?', 'date'=>'2019-12-16', 'id_users'=>'9', 'id_events'=>'3']);
                                                                                                                                                                                                                                                                                                                                                                                                                                                        $obj = App\Post::create(['text'=>'Pour la lumière !', 'date'=>'2019-12-23', 'id_users'=>'5', 'id_events'=>'3']);
                                                                                                                                                                                                                                                                                                                                                                                                                                                       $obj = App\Post::create(['text'=>'De mieux en mieux.', 'date'=>'2019-12-22', 'id_users'=>'6', 'id_events'=>'1']);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                     $obj = App\Post::create(['text'=>'Bof.', 'date'=>'2019-12-27', 'id_users'=>'2', 'id_events'=>'1']);
                                                                                                                                                                                                                                                                                                                                                                                                                                                 $obj = App\Post::create(['text'=>'Manque de membres actif.', 'date'=>'2019-12-29', 'id_users'=>'1', 'id_events'=>'2']);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                $obj = App\Post::create(['text'=>'Bonjour !', 'date'=>'2019-12-26', 'id_users'=>'3', 'id_events'=>'2']);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                $obj = App\Post::create(['text'=>'Génial !', 'date'=>'2019-12-03', 'id_users'=>'18', 'id_events'=>'4']);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  $obj = App\Post::create(['text'=>'Cool !', 'date'=>'2019-12-01', 'id_users'=>'16', 'id_events'=>'4']);
                                                                                                                                                                                                                                                                                                                                                                                                                                                $obj = App\Post::create(['text'=>'Pas compris le principe.', 'date'=>'2019-12-06', 'id_users'=>'14', 'id_events'=>'5']);
                                                               $obj = App\Post::create(['text'=>'Amet occaecat nisi qui et aute excepteur velit eiusmod dolor magna elit. Tempor tempor nisi est officia laborum pariatur irure anim aute exercitation culpa eu occaecat excepteur. Cupidatat occaecat culpa sint aliquip cillum laborum magna officia cillum occaecat. Cupidatat dolor dolor esse cillum enim ea. Commodo nulla ex Lorem incididunt officia irure in cupidatat dolor Lorem Lorem commodo.', 'date'=>'2019-12-07', 'id_users'=>'12', 'id_events'=>'5']);
       $obj = App\Post::create(['text'=>'Lorem cillum quis ad commodo eiusmod ad ut incididunt reprehenderit in nisi. Enim et deserunt qui ut. Nostrud do anim aliqua qui nisi veniam quis magna cillum. Ipsum et commodo officia cillum. Sint pariatur est officia sint reprehenderit ad irure proident pariatur deserunt incididunt officia duis cupidatat. Aute deserunt tempor cupidatat est adipisicing sit magna culpa Lorem non aute esse Lorem. Eu anim est elit amet anim minim dolor Lorem amet.', 'date'=>'2019-12-09', 'id_users'=>'16', 'id_events'=>'5']);
                                                                                                                                                                                                                                                                                                                                                                                                                                                              $obj = App\Post::create(['text'=>'Trop long.', 'date'=>'2019-12-15', 'id_users'=>'14', 'id_events'=>'7']);
                                                                                                                                                                                                                                                                                                                                                                                                                                    $obj = App\Post::create(['text'=>'Venez nombreux, on a besoin de monde', 'date'=>'2019-12-13', 'id_users'=>'12', 'id_events'=>'7']);
                                                                                                                                                                                                                                                                                                                                                                                             $obj = App\Post::create(['text'=>'Ea commodo ad voluptate ea sunt qui anim do sit excepteur nostrud sint qui.', 'date'=>'2019-12-12', 'id_users'=>'17', 'id_events'=>'7']);
                                                                                                                                                                                                                                                                                                                                                                                                                                                   $obj = App\Post::create(['text'=>'Il faut plus de bois.', 'date'=>'2019-12-13', 'id_users'=>'19', 'id_events'=>'4']);
                                                                                                                                                                                                                                                                                                                                                                                                                                                             $obj = App\Post::create(['text'=>'Très bien ?', 'date'=>'2019-12-11', 'id_users'=>'16', 'id_events'=>'6']);
                                                                                                                                                                                                                                                                                                                                                                                                                                                       $obj = App\Post::create(['text'=>'Pour la lumière !', 'date'=>'2019-12-29', 'id_users'=>'13', 'id_events'=>'6']);
                                                                                                                                                                                                                                                                                                                                                                                                                                                      $obj = App\Post::create(['text'=>'De mieux en mieux.', 'date'=>'2019-12-27', 'id_users'=>'11', 'id_events'=>'6']);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $obj = App\Post::create(['text'=>'Bof.', 'date'=>'2019-12-26', 'id_users'=>'14', 'id_events'=>'4']);
                                                                                                                                                                                                                                                                                                                                                                                                                                                $obj = App\Post::create(['text'=>'Manque de membres actif.', 'date'=>'2019-12-23', 'id_users'=>'16', 'id_events'=>'4']);
                                                                                                                                                                                                                                                                                                                                                                                                                                                               $obj = App\Post::create(['text'=>'Bonjour !', 'date'=>'2019-12-20', 'id_users'=>'19', 'id_events'=>'4']);
                                                                                                                                                                                                                                                                                                                                                                                                                                                               $obj = App\Post::create(['text'=>'Génial !', 'date'=>'2019-12-07', 'id_users'=>'20', 'id_events'=>'8']);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $obj = App\Post::create(['text'=>'Cool !', 'date'=>'2019-12-09', 'id_users'=>'28', 'id_events'=>'8']);
                                                                                                                                                                                                                                                                                                                                                                                                                                               $obj = App\Post::create(['text'=>'Pas compris le principe.', 'date'=>'2019-12-05', 'id_users'=>'26', 'id_events'=>'8']);
                                                              $obj = App\Post::create(['text'=>'Amet occaecat nisi qui et aute excepteur velit eiusmod dolor magna elit. Tempor tempor nisi est officia laborum pariatur irure anim aute exercitation culpa eu occaecat excepteur. Cupidatat occaecat culpa sint aliquip cillum laborum magna officia cillum occaecat. Cupidatat dolor dolor esse cillum enim ea. Commodo nulla ex Lorem incididunt officia irure in cupidatat dolor Lorem Lorem commodo.', 'date'=>'2019-12-01', 'id_users'=>'24', 'id_events'=>'8']);
      $obj = App\Post::create(['text'=>'Lorem cillum quis ad commodo eiusmod ad ut incididunt reprehenderit in nisi. Enim et deserunt qui ut. Nostrud do anim aliqua qui nisi veniam quis magna cillum. Ipsum et commodo officia cillum. Sint pariatur est officia sint reprehenderit ad irure proident pariatur deserunt incididunt officia duis cupidatat. Aute deserunt tempor cupidatat est adipisicing sit magna culpa Lorem non aute esse Lorem. Eu anim est elit amet anim minim dolor Lorem amet.', 'date'=>'2019-12-03', 'id_users'=>'26', 'id_events'=>'8']);
                                                                                                                                                                                                                                                                                                                                                                                                                                                             $obj = App\Post::create(['text'=>'Trop long.', 'date'=>'2019-12-19', 'id_users'=>'27', 'id_events'=>'8']);
                                                                                                                                                                                                                                                                                                                                                                                                                                   $obj = App\Post::create(['text'=>'Venez nombreux, on a besoin de monde', 'date'=>'2019-12-16', 'id_users'=>'29', 'id_events'=>'9']);
                                                                                                                                                                                                                                                                                                                                                                                            $obj = App\Post::create(['text'=>'Ea commodo ad voluptate ea sunt qui anim do sit excepteur nostrud sint qui.', 'date'=>'2019-12-17', 'id_users'=>'22', 'id_events'=>'9']);
                                                                                                                                                                                                                                                                                                                                                                                                                                                  $obj = App\Post::create(['text'=>'Il faut plus de bois.', 'date'=>'2019-12-13', 'id_users'=>'20', 'id_events'=>'9']);
                                                                                                                                                                                                                                                                                                                                                                                                                                                            $obj = App\Post::create(['text'=>'Très bien ?', 'date'=>'2019-12-11', 'id_users'=>'24', 'id_events'=>'11']);
                                                                                                                                                                                                                                                                                                                                                                                                                                                      $obj = App\Post::create(['text'=>'Pour la lumière !', 'date'=>'2019-12-23', 'id_users'=>'23', 'id_events'=>'10']);
                                                                                                                                                                                                                                                                                                                                                                                                                                                     $obj = App\Post::create(['text'=>'De mieux en mieux.', 'date'=>'2019-12-24', 'id_users'=>'21', 'id_events'=>'10']);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                   $obj = App\Post::create(['text'=>'Bof.', 'date'=>'2019-12-27', 'id_users'=>'26', 'id_events'=>'10']);
                                                                                                                                                                                                                                                                                                                                                                                                                                               $obj = App\Post::create(['text'=>'Manque de membres actif.', 'date'=>'2019-12-26', 'id_users'=>'28', 'id_events'=>'9']);
                                                                                                                                                                                                                                                                                                                                                                                                                                                              $obj = App\Post::create(['text'=>'Bonjour !', 'date'=>'2019-12-28', 'id_users'=>'29', 'id_events'=>'9']);
                                                                                                                                                                                                                                                                                                                                                                                                                                                              $obj = App\Post::create(['text'=>'Génial !', 'date'=>'2020-01-05', 'id_users'=>'30', 'id_events'=>'12']);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                $obj = App\Post::create(['text'=>'Cool !', 'date'=>'2020-01-09', 'id_users'=>'39', 'id_events'=>'12']);
                                                                                                                                                                                                                                                                                                                                                                                                                                              $obj = App\Post::create(['text'=>'Pas compris le principe.', 'date'=>'2020-01-06', 'id_users'=>'34', 'id_events'=>'12']);
                                                             $obj = App\Post::create(['text'=>'Amet occaecat nisi qui et aute excepteur velit eiusmod dolor magna elit. Tempor tempor nisi est officia laborum pariatur irure anim aute exercitation culpa eu occaecat excepteur. Cupidatat occaecat culpa sint aliquip cillum laborum magna officia cillum occaecat. Cupidatat dolor dolor esse cillum enim ea. Commodo nulla ex Lorem incididunt officia irure in cupidatat dolor Lorem Lorem commodo.', 'date'=>'2020-01-07', 'id_users'=>'36', 'id_events'=>'11']);
     $obj = App\Post::create(['text'=>'Lorem cillum quis ad commodo eiusmod ad ut incididunt reprehenderit in nisi. Enim et deserunt qui ut. Nostrud do anim aliqua qui nisi veniam quis magna cillum. Ipsum et commodo officia cillum. Sint pariatur est officia sint reprehenderit ad irure proident pariatur deserunt incididunt officia duis cupidatat. Aute deserunt tempor cupidatat est adipisicing sit magna culpa Lorem non aute esse Lorem. Eu anim est elit amet anim minim dolor Lorem amet.', 'date'=>'2020-01-02', 'id_users'=>'37', 'id_events'=>'11']);
                                                                                                                                                                                                                                                                                                                                                                                                                                                            $obj = App\Post::create(['text'=>'Trop long.', 'date'=>'2020-01-16', 'id_users'=>'38', 'id_events'=>'12']);
                                                                                                                                                                                                                                                                                                                                                                                                                                  $obj = App\Post::create(['text'=>'Venez nombreux, on a besoin de monde', 'date'=>'2020-01-13', 'id_users'=>'36', 'id_events'=>'12']);
                                                                                                                                                                                                                                                                                                                                                                                           $obj = App\Post::create(['text'=>'Ea commodo ad voluptate ea sunt qui anim do sit excepteur nostrud sint qui.', 'date'=>'2020-01-11', 'id_users'=>'33', 'id_events'=>'11']);
                                                                                                                                                                                                                                                                                                                                                                                                                                                 $obj = App\Post::create(['text'=>'Il faut plus de bois.', 'date'=>'2020-01-14', 'id_users'=>'31', 'id_events'=>'13']);
                                                                                                                                                                                                                                                                                                                                                                                                                                                           $obj = App\Post::create(['text'=>'Très bien ?', 'date'=>'2020-01-15', 'id_users'=>'34', 'id_events'=>'13']);
                                                                                                                                                                                                                                                                                                                                                                                                                                                     $obj = App\Post::create(['text'=>'Pour la lumière !', 'date'=>'2020-01-27', 'id_users'=>'35', 'id_events'=>'13']);
                                                                                                                                                                                                                                                                                                                                                                                                                                                    $obj = App\Post::create(['text'=>'De mieux en mieux.', 'date'=>'2020-01-29', 'id_users'=>'39', 'id_events'=>'14']);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  $obj = App\Post::create(['text'=>'Bof.', 'date'=>'2020-01-23', 'id_users'=>'37', 'id_events'=>'14']);
                                                                                                                                                                                                                                                                                                                                                                                                                                              $obj = App\Post::create(['text'=>'Manque de membres actif.', 'date'=>'2020-01-29', 'id_users'=>'35', 'id_events'=>'14']);
                                                                                                                                                                                                                                                                                                                                                                                                                                                             $obj = App\Post::create(['text'=>'Bonjour !', 'date'=>'2020-01-28', 'id_users'=>'39', 'id_events'=>'1']);
                                                                                                                                                                                                                                                                                                                                                                                                                                                             $obj = App\Post::create(['text'=>'Génial !', 'date'=>'2020-02-09', 'id_users'=>'50', 'id_events'=>'2']);
                                                                                                                                                                                                                                                                                                                                                                                                                                                               $obj = App\Post::create(['text'=>'Cool !', 'date'=>'2020-02-04', 'id_users'=>'52', 'id_events'=>'4']);
                                                                                                                                                                                                                                                                                                                                                                                                                                             $obj = App\Post::create(['text'=>'Pas compris le principe.', 'date'=>'2020-02-07', 'id_users'=>'59', 'id_events'=>'3']);
                                                            $obj = App\Post::create(['text'=>'Amet occaecat nisi qui et aute excepteur velit eiusmod dolor magna elit. Tempor tempor nisi est officia laborum pariatur irure anim aute exercitation culpa eu occaecat excepteur. Cupidatat occaecat culpa sint aliquip cillum laborum magna officia cillum occaecat. Cupidatat dolor dolor esse cillum enim ea. Commodo nulla ex Lorem incididunt officia irure in cupidatat dolor Lorem Lorem commodo.', 'date'=>'2020-02-06', 'id_users'=>'57', 'id_events'=>'2']);
    $obj = App\Post::create(['text'=>'Lorem cillum quis ad commodo eiusmod ad ut incididunt reprehenderit in nisi. Enim et deserunt qui ut. Nostrud do anim aliqua qui nisi veniam quis magna cillum. Ipsum et commodo officia cillum. Sint pariatur est officia sint reprehenderit ad irure proident pariatur deserunt incididunt officia duis cupidatat. Aute deserunt tempor cupidatat est adipisicing sit magna culpa Lorem non aute esse Lorem. Eu anim est elit amet anim minim dolor Lorem amet.', 'date'=>'2020-02-02', 'id_users'=>'55', 'id_events'=>'7']);
                                                                                                                                                                                                                                                                                                                                                                                                                                                           $obj = App\Post::create(['text'=>'Trop long.', 'date'=>'2020-02-13', 'id_users'=>'56', 'id_events'=>'8']);
                                                                                                                                                                                                                                                                                                                                                                                                                                 $obj = App\Post::create(['text'=>'Venez nombreux, on a besoin de monde', 'date'=>'2020-02-16', 'id_users'=>'53', 'id_events'=>'5']);
                                                                                                                                                                                                                                                                                                                                                                                          $obj = App\Post::create(['text'=>'Ea commodo ad voluptate ea sunt qui anim do sit excepteur nostrud sint qui.', 'date'=>'2020-02-11', 'id_users'=>'51', 'id_events'=>'6']);
                                                                                                                                                                                                                                                                                                                                                                                                                                                $obj = App\Post::create(['text'=>'Il faut plus de bois.', 'date'=>'2020-02-10', 'id_users'=>'58', 'id_events'=>'2']);
                                                                                                                                                                                                                                                                                                                                                                                                                                                          $obj = App\Post::create(['text'=>'Très bien ?', 'date'=>'2020-02-14', 'id_users'=>'55', 'id_events'=>'4']);
                                                                                                                                                                                                                                                                                                                                                                                                                                                    $obj = App\Post::create(['text'=>'Pour la lumière !', 'date'=>'2020-02-27', 'id_users'=>'55', 'id_events'=>'2']);
                                                                                                                                                                                                                                                                                                                                                                                                                                                   $obj = App\Post::create(['text'=>'De mieux en mieux.', 'date'=>'2020-02-28', 'id_users'=>'56', 'id_events'=>'3']);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $obj = App\Post::create(['text'=>'Bof.', 'date'=>'2020-02-23', 'id_users'=>'65', 'id_events'=>'2']);
                                                                                                                                                                                                                                                                                                                                                                                                                                             $obj = App\Post::create(['text'=>'Manque de membres actif.', 'date'=>'2020-02-22', 'id_users'=>'25', 'id_events'=>'1']);
                                                                                                                                                                                                                                                                                                                                                                                                                                                            $obj = App\Post::create(['text'=>'Bonjour !', 'date'=>'2020-02-23', 'id_users'=>'75', 'id_events'=>'2']);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        //
    }
}
